### ISSUE TITLE
Can you help me to fix ERROR #85901  GRAPHQL

### ISSUE THREAD

**Issue by Esantomi** [theowenyoung/gatsby-starter-primer-wiki#1]
I have an issue on build, kinda Graphql thing but I can't barely fix it.

can you help me to fix it?

![image](https://user-images.githubusercontent.com/61646760/162558714-b493f7ad-7be5-40ea-bc95-0434ee018f25.png)
![image](https://user-images.githubusercontent.com/61646760/162558804-8896a7e1-be41-4234-a1c5-19099fe6baed.png)

**Comment by theowenyoung** [comment]
Hi, @Esantomi , try again. I have updated this repo's dependences. Now it works.

**Comment by Esantomi** [comment]
> Hi, @Esantomi , try again. I have updated this repo's dependences. Now it works.

it works well. thank you so much!!
